---
title: "Run Canek on Seurat objects"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use Canek with Seurat}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.align = "center",
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Canek)
library(Seurat)
library(ggplot2)
```

# Create Seurat object

```{r}
x <- lapply(names(SimBatches$batches), function(batch) {
  CreateSeuratObject(SimBatches$batches[[batch]], project = batch) 
})
x <- merge(x[[1]], x[[2]])
x[["cell_type"]] <- SimBatches$cell_types
x
```

```{r}
table(x$orig.ident)
```

```{r}
x <- NormalizeData(x)
x <- FindVariableFeatures(x)
VariableFeaturePlot(x)
```

```{r}
x <- ScaleData(x)
```

```{r}
x <- RunPCA(x, verbose = FALSE)
```

## PCA plot before correction

```{r}
ElbowPlot(x)
DimPlot(x, group.by = "orig.ident")
DimPlot(x, group.by = "cell_type")
```

# Run Canek

We pass the column containing the batch information.

```{r}
dims <- 10
x1 <- RunCanek(x, "orig.ident", correctEmbeddings = TRUE, pcaDim = dims)
x2 <- RunCanek(x, "orig.ident", correctEmbeddings = FALSE)
```

```{r}
x1
x2
```


We scale features and run PCA.

```{r}
x2 <- ScaleData(x2, verbose = FALSE)
x2 <- RunPCA(x2, verbose = FALSE, npcs = dims)
```

```{r}
x1 <- RunUMAP(object = x1, reduction = "canek", dims = 1:dims, verbose = FALSE)
x2 <- RunUMAP(object = x2, reduction = "pca", dims = 1:dims, verbose = FALSE)
```


## PCA plot after correction

```{r fig.width=4}
DimPlot(x2,  group.by = "orig.ident") + DimPlot(x2, group.by = "cell_type") & coord_fixed() & ggtitle("Old")
DimPlot(x1,  group.by = "orig.ident") + DimPlot(x1,  group.by = "cell_type") & coord_fixed() & ggtitle("New")
```
